### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by Ahmed-Ly** [Allerek/MTASA-NativeUI#15]
ERROR: NativeUI\main.lua:244: attempt to index field 'items' (a nil value) 
i get this error then  i try close  menu and some items  dont display

**Comment by Bonaro** [comment]
Hello, please comment your code so we can analyze

**Comment by Ahmed-Ly** [comment]
`NativeUI  = exports.NativeUI


function  OpenNativeUI (bool) 
    if type(bool) ==  "boolean" then  
   open = bool 
    else 
  outputDebugString("Bad argument 1 @ OpenNativeUI [Number expected, got " .. type(bool) .. "]")
    end
end 

function isNativeUIOpen()
 return open
end 
OpenNativeUI (false) 
addCommandHandler("wallhack", function ()
    if isNativeUIOpen() == false then   
 menu3 = NativeUI:createNativeUI("WALLHACK","BY Ahmed Ly","assets/defaultbg.png",tocolor(255,255,255), tocolor(255,255,255), tocolor(255, 255, 255),"right",true,10, "left")
 NativeUI:addNativeButton("Activate",tocolor(255,255,255),"ammo")
 NativeUI:addNativeButton("Not Activated",tocolor(255,255,255),"ammo")
 NativeUI:addNativeButton("Close menu",tocolor(255,255,255),"ammo")
 OpenNativeUI(true) 
end
end )


addEventHandler("onClientAcceptButton", getRootElement(), function(id, text)
    if id == 3 then 
        --[[
     for i = 1,3 do 
            NativeUI:removeNativeItem(i)
          end 
          --]]
            NativeUI:removeNativeUI(menu3)
        OpenNativeUI(false) 
    end
end)` its work fine then start resource but after press close and open menu again will see a lot bugs

**Comment by Bonaro** [comment]
You do not need to store the menu within a variable, and when removing the menu you do not need to pass any parameters. NativeUI allows only one menu to be created at a time.

**Comment by Ahmed-Ly** [comment]
how to removed and started again  i must use clearNativeUI or removeNativeUI how?? : ( i use two this functions without parameters And i dont use variables

**Comment by Ahmed-Ly** [comment]
Help

**Comment by Ahmed-Ly** [comment]
@Bonaro

**Comment by Bonaro** [comment]
I don't know what that could be, but you can fix this problem yourself in the project, it's open source.

**Comment by Allerek** [comment]
Project is no longer supported so you have to fix problem yourself. Closed.
