### ISSUE TITLE
Add Function "setNativeSwitchSelected"

### ISSUE THREAD

**Issue by Bonaro** [Allerek/MTASA-NativeUI#3]
This function will set the value of the switch, for example the switch has the possible values ​​"Good", "Great", "Bad. This function will set the selected value to any of the possible values ​​for example" setNativeSwitchSelected (1, "Bad" ) ", when executed the value of the Switch will be" Bad ", if the function is executed and the value does not exist in the switch, an error will occur.

**Comment by Allerek** [comment]
Implemented in next update
