### ISSUE TITLE
Add Function "setNativePlaceHolderIcon"

### ISSUE THREAD

**Issue by Bonaro** [Allerek/MTASA-NativeUI#5]
This function will set an icon for the Placeholder for example "setNativePlaceHolderIcon(1," clothing ")", this will add the clothing icon to PlaceHolder, if the icon does not exist an error will occur. See an icon in the image below.

![20190911003340_1](https://user-images.githubusercontent.com/46500752/64667988-3be7a180-d432-11e9-880d-aedce4891ffa.jpg)

**Comment by Allerek** [comment]
Accepted, will be implemented in next version.
